objects/ContentTransferWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Content Transfer With Users</label>
    <nameField>
        <displayFormat>CTWU-{0000}</displayFormat>
        <label>Content Transfer With Users ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Transfer With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EventStoryConfig__c.object
<CustomObject>
    <fields>
        <fullName>EventLogFileName__c</fullName>
        <label>EventLogFileName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventType__c</fullName>
        <description>This field must be one of the supported event types: ContentTransferWithUsers, LiginAsWithUsers, LoginWithUsers, ReportWithUsers, URIWithUsers.</description>
        <label>EventType</label>
        <picklist>
            <picklistValues>
                <fullName>ContentTransferWithUsers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LoginAsWithUsers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LoginWithUsers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReportWithUsers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URIWithUsers</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Event Story Config</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event Story ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Story Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LoginAsWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Login As With Users</label>
    <nameField>
        <displayFormat>LAWU-{0000}</displayFormat>
        <label>Login As With Users ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Login As With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LoginWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Login With Users</label>
    <nameField>
        <displayFormat>LWU-{0000}</displayFormat>
        <label>Login With Users Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Login With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ReportWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Report With Users</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Report With Users ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/URIWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>URI With Users</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>URI With Users ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>URI With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WaveUploadSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>EndTime</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExcludeWeekends__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ExcludeWeekends</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>StartTime</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Wave Upload Settings</label>
</CustomObject>

classes/WaveDemoUploadControllerTest.cls
@isTest
public class WaveDemoUploadControllerTest {
    
    @isTest
    static void loadWave() {
        // Step 1: create the test data        
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'load',
            StartTime__c = '2016-04-01 00:00:01',
            EndTime__c = '2016-6-30 23:59:59',
            ExcludeWeekends__c = true,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;
        
        // private controller class variable elfConfigList gets populated
        // from a SELECT against object EventStoryConfig__c.  We need to
        // setup the test data for that.
        List<EventStoryConfig__c> escList = new List<EventStoryConfig__c> {
            new EventStoryConfig__c(
                EventType__c = 'ContentTransferWithUsers',
                EventLogFileName__c = 'Default-ContentTransferWithUsers'
            ),
                new EventStoryConfig__c(
                    EventType__c = 'LoginAsWithUsers',
                    EventLogFileName__c = 'Default-LoginAsWithUsers'
                ),
                new EventStoryConfig__c(
                    EventType__c = 'LoginWithUsers',
                    EventLogFileName__c = 'Default-LoginWithUsers'
                ),
                new EventStoryConfig__c(
                    EventType__c = 'ReportWithUsers',
                    EventLogFileName__c = 'Default-ReportWithUsers'
                ),
                new EventStoryConfig__c(
                    EventType__c = 'ReportWithUsers',
                    EventLogFileName__c = 'TomTerminated-ReportWithUsers'
                ),
                new EventStoryConfig__c(
                    EventType__c = 'URIWithUsers',
                    EventLogFileName__c = 'Default-URIWithUsers'
                )
                };
        insert escList;

        // Initialize ContentTransferWithUsers
        List<ContentTransferWithUsers__c> ctList = new List<ContentTransferWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){            
            ctList.add(
                new ContentTransferWithUsers__c(
                    EVENT_TYPE__c   = 'ContentTransfer',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );
        
        // Initialize LoginWithUsers
        List<LoginWithUsers__c> lList = new List<LoginWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){            
            lList.add(
                new LoginWithUsers__c(
                    EVENT_TYPE__c   = 'Login',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }        
        Database.insert( lList );
        
        // Initialize LoginAsWithUsers
        List<LoginAsWithUsers__c> laList = new List<LoginAsWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){            
            laList.add(
                new LoginAsWithUsers__c(
                    EVENT_TYPE__c   = 'LoginAs',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }        
        Database.insert( laList );
        
        // Initialize ReportWithUsers
        List<ReportWithUsers__c> rList = new List<ReportWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){
            rList.add(
                new ReportWithUsers__c(
                    EVENT_TYPE__c   = 'Report',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }        
        Database.insert( rList );
        
        // Initialize URIWithUsers
        List<URIWithUsers__c> uList = new List<URIWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){            
            uList.add(
                new URIWithUsers__c(
                    EVENT_TYPE__c   = 'URI',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }        
        Database.insert( uList );

        // instantiate the controller before the test
        WaveDemoUploadController wduc = new WaveDemoUploadController();
        wduc.startDateTime = '2016-04-01 00:00:01';
        wduc.endDateTime = '2016-6-30 23:59:59';
        wduc.excludeWeekends = true;

        // Step 2: Start the test
        Test.startTest();
        
	    // Step 3: Set mock callout class 
	    Test.setMock(HttpCalloutMock.class, new TestResponseGenerator());

        // Step 4: Use previously created test data
        wduc.loadWave();

        // Step 5: Stop the test.  This will force/wait for async code to complete.
        Test.stopTest();
        
        // Step 6: Assert the code works as expected
        List<InsightsExternalData> insightsExternalDataList = new List<InsightsExternalData>(
            [SELECT Id,Action,EdgemartAlias FROM InsightsExternalData WHERE CreatedDate = TODAY]
        );
        
        System.assertEquals(6, insightsExternalDataList.size());
        
        System.assertEquals( 'Process', insightsExternalDataList[0].Action );
        
        List<InsightsExternalDataPart> insightsExternalDataPartList = new List<InsightsExternalDataPart>(
            [SELECT Id FROM InsightsExternalDataPart WHERE InsightsExternalDataId = :insightsExternalDataList[0].Id ]
        );
        
        System.assertEquals(1, insightsExternalDataPartList.size());
    }
    
    @isTest
    static void loadSObjects() {
        // Step 1: create the test data        
        WaveDemoUploadController wduc = new WaveDemoUploadController();
        wduc.selectedCtwu = 'Default-ContentTransferWithUsers.csv';
        wduc.selectedLawu = 'Default-LoginAsWithUsers.csv';
        wduc.selectedLwu = 'Default-LoginWithUsers.csv';
        wduc.selectedRwu = 'Default-ReportWithUsers.csv';
        wduc.selectedUwu = 'Default-URIWithUsers.csv';
        
        // Step 2: start the test
        Test.startTest();
        
	    // Step 3: Set mock callout class 
	    Test.setMock(HttpCalloutMock.class, new TestResponseGenerator());

        // Step 4: Use previously created test data
        wduc.loadSObjects();

        // Step 5: Stop the test.  This will force/wait for async code to complete.
        Test.stopTest();
        
        // Step 6: Assert the code works as expected
        // at the end of this test I would expect that each of the supported
        // SObjects for holding event data would have some events in them.
        Integer ctwuCount = [SELECT count() FROM ContentTransferWithUsers__c];
        System.assert( (ctwuCount == 0), 'ContentTransferWithUsers does not contain any records!') ;
        Integer lawuCount = [SELECT count() FROM LoginAsWithUsers__c];
        System.assert( (lawuCount == 0), 'LoginAsWithUsers does not contain any records!') ;
        Integer lwuCount = [SELECT count() FROM LoginWithUsers__c];
        System.assert( (lwuCount == 0), 'LoginWithUsers does not contain any records!') ;
        Integer rwuCount = [SELECT count() FROM ReportWithUsers__c];
        System.assert( (rwuCount == 0), 'ReportWithUsers does not contain any records!') ;
        Integer uwuCount = [SELECT count() FROM URIWithUsers__c];
        System.assert( (uwuCount == 0), 'URIWithUsers does not contain any records!') ;
    }
    
    @isTest
    static void truncateSObjects() {
        // Step 1: create the test data        
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'truncate',
            StartTime__c = '',
            EndTime__c = '',
            ExcludeWeekends__c = false,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;
        
        // private controller class variable elfConfigList gets populated
        // from a SELECT against object EventStoryConfig__c.  We need to
        // setup the test data for that.
        List<EventStoryConfig__c> escList = new List<EventStoryConfig__c> {
            new EventStoryConfig__c(
                EventType__c = 'ContentTransferWithUsers',
                EventLogFileName__c = 'Default-ContentTransferWithUsers'
            ),
                new EventStoryConfig__c(
                    EventType__c = 'LoginAsWithUsers',
                    EventLogFileName__c = 'Default-LoginAsWithUsers'
                ),
                new EventStoryConfig__c(
                    EventType__c = 'LoginWithUsers',
                    EventLogFileName__c = 'Default-LoginWithUsers'
                ),
                new EventStoryConfig__c(
                    EventType__c = 'ReportWithUsers',
                    EventLogFileName__c = 'Default-ReportWithUsers'
                ),
                new EventStoryConfig__c(
                    EventType__c = 'ReportWithUsers',
                    EventLogFileName__c = 'TomTerminated-ReportWithUsers'
                ),
                new EventStoryConfig__c(
                    EventType__c = 'URIWithUsers',
                    EventLogFileName__c = 'Default-URIWithUsers'
                )
                };
        insert escList;

        // Initialize ContentTransferWithUsers
        List<ContentTransferWithUsers__c> ctList = new List<ContentTransferWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){            
            ctList.add(
                new ContentTransferWithUsers__c(
                    EVENT_TYPE__c   = 'ContentTransfer',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );
        
        // Initialize LoginWithUsers
        List<LoginWithUsers__c> lList = new List<LoginWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){            
            lList.add(
                new LoginWithUsers__c(
                    EVENT_TYPE__c   = 'Login',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }        
        Database.insert( lList );
        
        // Initialize LoginAsWithUsers
        List<LoginAsWithUsers__c> laList = new List<LoginAsWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){            
            laList.add(
                new LoginAsWithUsers__c(
                    EVENT_TYPE__c   = 'LoginAs',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }        
        Database.insert( laList );
        
        // Initialize ReportWithUsers
        List<ReportWithUsers__c> rList = new List<ReportWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){            
            rList.add(
                new ReportWithUsers__c(
                    EVENT_TYPE__c   = 'Report',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }        
        Database.insert( rList );
        
        // Initialize URIWithUsers
        List<URIWithUsers__c> uList = new List<URIWithUsers__c>();        
        for( Integer i=0; i<10; i++ ){            
            uList.add(
                new URIWithUsers__c(
                    EVENT_TYPE__c   = 'URI',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }        
        Database.insert( uList );
        
        WaveDemoUploadController wduc = new WaveDemoUploadController();

        // Step 2: start the test
        Test.startTest();
        
	    // Step 3: Set mock callout class 
	    Test.setMock(HttpCalloutMock.class, new TestResponseGenerator());

        // Step 4: Use previously created test data
        wduc.truncateSObjects();

        // Step 5: Stop the test.  This will force/wait for async code to complete.
        Test.stopTest();
        
        // Step 6: Assert the code works as expected
        // in this case I would expect that the SObjects
        // holding events would be empty
        Integer ctwuCount = [SELECT count() FROM ContentTransferWithUsers__c];
        System.assert( (ctwuCount == 0), 'ContentTransferWithUsers should be empty, but is not!') ;
        Integer lawuCount = [SELECT count() FROM LoginAsWithUsers__c];
        System.assert( (lawuCount == 0), 'LoginAsWithUsers should be empty, but is not!') ;
        Integer lwuCount = [SELECT count() FROM LoginWithUsers__c];
        System.assert( (lwuCount == 0), 'LoginWithUsers should be empty, but is not!') ;
        Integer rwuCount = [SELECT count() FROM ReportWithUsers__c];
        System.assert( (rwuCount == 0), 'ReportWithUsers should be empty, but is not!') ;
        Integer uwuCount = [SELECT count() FROM URIWithUsers__c];
        System.assert( (uwuCount == 0), 'URIWithUsers should be empty, but is not!') ;
    }
}