objects/ContentTransferWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Content Transfer With Users</label>
    <nameField>
        <displayFormat>CTWU-{0000}</displayFormat>
        <label>Content Transfer With Users ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Transfer With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LoginAsWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Login As With Users</label>
    <nameField>
        <displayFormat>LAWU-{0000}</displayFormat>
        <label>Login As With Users ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Login As With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LoginWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Login With Users</label>
    <nameField>
        <displayFormat>LWU-{0000}</displayFormat>
        <label>Login With Users Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Login With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ReportWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Report With Users</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Report With Users ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/URIWithUsers__c.object
<CustomObject>
    <fields>
        <fullName>EVENT_TYPE__c</fullName>
        <label>EVENT_TYPE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORGANIZATION_ID__c</fullName>
        <label>ORGANIZATION_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP_DERIVED__c</fullName>
        <label>TIMESTAMP_DERIVED</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIMESTAMP__c</fullName>
        <label>TIMESTAMP</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>URI With Users</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>URI With Users ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>URI With Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WaveUploadSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>EndTime</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExcludeWeekends__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ExcludeWeekends</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>StartTime</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Wave Upload Settings</label>
</CustomObject>

classes/EventLogFilesTest.cls
@IsTest
public class EventLogFilesTest {

    static testmethod void testContentTransferWithUsersLoad() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'load',
            StartTime__c = '2016-04-01 00:00:01',
            EndTime__c = '2016-6-30 23:59:59',
            ExcludeWeekends__c = true,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize ContentTransferWithUsers
        List<ContentTransferWithUsers__c> ctList = new List<ContentTransferWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new ContentTransferWithUsers__c(
                    EVENT_TYPE__c   = 'ContentTransfer',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       ContentTransferWithUsers c = new ContentTransferWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM ContentTransferWithUsers__c];
       System.assert((i > 0), 'Expected more than zero items in ContentTransferWithUsers__c.');
    }

    static testmethod void testContentTransferWithUsersTruncate() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'truncate',
            StartTime__c = '',
            EndTime__c = '',
            ExcludeWeekends__c = false,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize ContentTransferWithUsers
        List<ContentTransferWithUsers__c> ctList = new List<ContentTransferWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new ContentTransferWithUsers__c(
                    EVENT_TYPE__c   = 'ContentTransfer',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       ContentTransferWithUsers c = new ContentTransferWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM ContentTransferWithUsers__c];
       System.assert((i == 0), 'Expected zero items in ContentTransferWithUsers__c.');
    }

    static testmethod void testLoginAsWithUsersLoad() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'load',
            StartTime__c = '2016-04-01 00:00:01',
            EndTime__c = '2016-6-30 23:59:59',
            ExcludeWeekends__c = true,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize LoginAsWithUsers
        List<LoginAsWithUsers__c> ctList = new List<LoginAsWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new LoginAsWithUsers__c(
                    EVENT_TYPE__c   = 'LoginAs',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       LoginAsWithUsers c = new LoginAsWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM LoginAsWithUsers__c];
       System.assert((i > 0), 'Expected more than zero items in LoginAsWithUsers__c.');
    }

    static testmethod void testLoginAsWithUsersTruncate() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'truncate',
            StartTime__c = '',
            EndTime__c = '',
            ExcludeWeekends__c = false,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize LoginAsWithUsers
        List<LoginAsWithUsers__c> ctList = new List<LoginAsWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new LoginAsWithUsers__c(
                    EVENT_TYPE__c   = 'LoginAs',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       LoginAsWithUsers c = new LoginAsWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM LoginAsWithUsers__c];
       System.assert((i == 0), 'Expected zero items in LoginAsWithUsers__c.');
    }

    static testmethod void testLoginWithUsersLoad() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'load',
            StartTime__c = '2016-04-01 00:00:01',
            EndTime__c = '2016-6-30 23:59:59',
            ExcludeWeekends__c = true,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize LoginWithUsers
        List<LoginWithUsers__c> ctList = new List<LoginWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new LoginWithUsers__c(
                    EVENT_TYPE__c   = 'Login',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       LoginWithUsers c = new LoginWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM LoginWithUsers__c];
       System.assert((i > 0), 'Expected more than zero items in LoginWithUsers__c.');
    }

    static testmethod void testLoginWithUsersTruncate() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'truncate',
            StartTime__c = '',
            EndTime__c = '',
            ExcludeWeekends__c = false,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize LoginWithUsers
        List<LoginWithUsers__c> ctList = new List<LoginWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new LoginWithUsers__c(
                    EVENT_TYPE__c   = 'Login',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       LoginWithUsers c = new LoginWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM LoginWithUsers__c];
       System.assert((i == 0), 'Expected zero items in LoginWithUsers__c.');
    }
    
    static testmethod void testReportWithUsersLoad() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'load',
            StartTime__c = '2016-04-01 00:00:01',
            EndTime__c = '2016-6-30 23:59:59',
            ExcludeWeekends__c = true,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize ReportWithUsers
        List<ReportWithUsers__c> ctList = new List<ReportWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new ReportWithUsers__c(
                    EVENT_TYPE__c   = 'Report',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       ReportWithUsers c = new ReportWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM ReportWithUsers__c];
       System.assert((i > 0), 'Expected more than zero items in ReportWithUsers__c.');
    }

    static testmethod void testReportWithUsersTruncate() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'truncate',
            StartTime__c = '',
            EndTime__c = '',
            ExcludeWeekends__c = false,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize ReportWithUsers
        List<ReportWithUsers__c> ctList = new List<ReportWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new ReportWithUsers__c(
                    EVENT_TYPE__c   = 'Report',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       ReportWithUsers c = new ReportWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM ReportWithUsers__c];
       System.assert((i == 0), 'Expected zero items in ReportWithUsers__c.');
    }
    
    static testmethod void testURIWithUsersLoad() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'load',
            StartTime__c = '2016-04-01 00:00:01',
            EndTime__c = '2016-6-30 23:59:59',
            ExcludeWeekends__c = true,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize URIWithUsers
        List<URIWithUsers__c> ctList = new List<URIWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new URIWithUsers__c(
                    EVENT_TYPE__c   = 'URI',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       URIWithUsers c = new URIWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM URIWithUsers__c];
       System.assert((i > 0), 'Expected more than zero items in URIWithUsers__c.');
    }

    static testmethod void testURIWithUsersTruncate() {
        // Set processing context
        WaveUploadSettings__c newWus = new WaveUploadSettings__c(
            Operation__c = 'truncate',
            StartTime__c = '',
            EndTime__c = '',
            ExcludeWeekends__c = false,
            Name = 'SObjectMgmtConfig'
        );
        insert newWus;

        // Initialize URIWithUsers
        List<URIWithUsers__c> ctList = new List<URIWithUsers__c>();
        
        for( Integer i=0; i<10; i++ ){
            
            ctList.add(
                new URIWithUsers__c(
                    EVENT_TYPE__c   = 'URI',
                    ORGANIZATION_ID__c  = '00D36000001DsqM',
                    TIMESTAMP__c    = DateTime.now().format('yyyyMMddHHmmss'),
                    TIMESTAMP_DERIVED__c = DateTime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                )
            );
        }
        Database.insert( ctList );

       Test.startTest();
       URIWithUsers c = new URIWithUsers();
       Database.executeBatch(c);
       Test.stopTest();

       // Difficult to test whether items got loaded into Wave 
       Integer i = [SELECT COUNT() FROM URIWithUsers__c];
       System.assert((i == 0), 'Expected zero items in URIWithUsers__c.');
    }
    
}